project_id = "zgexnqpeywpsbrkrfrsu"

[functions.generate-topic]
verify_jwt = false

[functions.evaluate-reading]
verify_jwt = false

[functions.get-daily-topic]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.generate-competition]
verify_jwt = false

[functions.generate-daily-prophecy]
verify_jwt = false

[functions.generate-topic-links]
verify_jwt = false

[functions.get-vapid-key]
verify_jwt = false
